category_name = "Achievements & Unlockables"
category_color = 0xF7CB15
category_description = { _ = "Items which are used for achievements or unlockable mounts. Most of them lose their value, once the achievement or mount is unlocked." }
mergeable = true
merged_by_default = false

[lizi]
name = "Lizis Reins (Mount)"
description = { _ = "A mount that can be unlocked in Ohn'iri Springs in the Ohn'ahran Plains. Requires to hand in one of these items once a day." }
color = 0x878E88
items = [192615, 192658, 194966, 192636, 200598]

[honor]
name = "Honor Our Ancestors"
description = { _ = "CONTAINS ITEMS FROM OTHER CATEGORIES! These items can be handed in the Ohn'ahran Plains (while under the effect of Essence of Awakening) to get this achievement." }
color = 0x76BED0
enabled_by_default = false
items = [191471, 197776, 200018, 194690, 202070, 193470, 190327, 197788, 199049]

[temperamental_skyclaw]
name = "Temperamental Skyclaw (Mount)"
description = { _ = "To get Temperamental Skyclaw you have to collect these 3 types of food and turn it to Zon'Wogi Stable Master at Three-Falls Lookout (Azure Span)." }
color = 0xF55D3E
items = [201420, 201421, 201422]

[magmashell]
name = "Magmashell (Mount)"
description = { _ = "This category only contains the Empty Magma Shell required to get the Magmashell Mount in the Waking Shores." }
color = 0xFF8C61
items = [201883]

[slumbering_worldsnail]
name = "Scrappy Worldsnail (Mount)"
description = { _ = "This category only contains the Membership and the Magmotes required to get the Scrappy Worldsnail Mount in the Waking Shores." }
color = 0xCE6A85
items = [199215, 202173]

[the_way_to_an_ottos_heart]
name = "Otto (Mount)"
description = { _ = "This section contains items which are needed to unlock Otto, the fishing ottusk mount." }
color = 0x1d24e2
items = [
    199338,
    199339,
    199340,
    202061,
    202066,
    202068,
    202069,
    202072,
    202073,
    202074,
    202102,
]

[tetrachromancer]
name = "Tetrachromancer (Achievement)"
description = { _ = "This category contains hunting companion colors needed for the achievement." }
color = 0xFCCCBF
items = [193205, 194087, 194088, 194089, 194090, 194091, 194093, 194094, 194095]

[librarian_of_the_reach]
name = "Librarian of the Reach (Achievement)"
description = { _ = "This category contains the books looted for the Librarian of the Reach achievement." }
color = 0xE69AFF
items = [204181, 204185, 204316, 204317, 204321, 204328, 204335, 204338, 204691]

[while_we_were_sleeping]
name = "While We Were Sleeping (Achievement)"
description = { _ = "This category contains the quest items looted for the While We Were Sleeping achievement." }
color = 0x00D441
items = [
    202203,
    202326,
    202327,
    202328,
    202329,
    202335,
    202336,
    202337,
    204200,
    204221,
    204223,
    204246,
    204250,
    204251,
    204252,
    204253,
]


[chip_pet]
name = "Chip (Pet)"
description = { _ = "This category contains the items needed to get the Chip pet." }
color = 0xDEFF00
items = [198082, 198357, 199219]

[phoenix_wishwing_pet]
name = "Phoenix Wishwing (Pet)"
description = { _ = "This category contains the items needed to get the Phoenix Wishwing pet." }
color = 0xFF9600
items = [199080, 199092, 199097, 199099, 199177, 199203, 202062]
